[screen]
width = 640
height = 640

[grid]
width = 30
height = 30

[colors]
background_color = "#323232"
line_color = "#c8c8c8"
cell_color = "#afafaf"
red_color = "#960000"

[game]
alive_chance = 2
tick_millis = 150
